services:
  gstreamer:
    build:
      context: .  # Ruta al directorio con el Dockerfile
      dockerfile: Dockerfile_ServerVideo
    container_name: gstreamer
#    ports:
     # - "5006:5000/udp"
     # - "5007:5001/udp"
     # - "5008:5002/udp"
     # - "5009:5003/udp"
     # - "5010:5004/udp"
     # - "5011:5005/udp"
    devices:
      # Permite al contenedor acceder a los dispositivos de video (ajusta la ruta de los dispositivos)
      - /dev/bus/usb/002/004:/dev/bus/usb/002/004
<<<<<<< HEAD
      - /dev/bus/usb/002/005:/dev/bus/usb/002/005
      - /dev/bus/usb/003/002:/dev/bus/usb/003/002
=======
      #- "/dev/video1:/dev/video1"
>>>>>>> 03022cd939abe2f3f7bc1d77299404bf0b988796
    volumes:
      - ./gstreamer/start_gstreamer.sh:/Gstreamer/start_gstreamer.sh
    restart: no
    network_mode: "host"
    privileged: true
  
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
 #   ports:
      #- 5000:5000/udp           # RTP cam1
      #- 5001:5001/udp           # RTCP cam1
      #- 5002:5002/udp           # RTP cam2
      #- 5003:5003/udp           # RTCP cam2
      #- 5004:5004/udp           # RTP cam3
      #- 5005:5005/udp           # RTCP cam3 
      #- 8554:8554
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
<<<<<<< HEAD
=======
    network_mode: "host"
 
  front:  # Contenedor para tu aplicación PySide6 + GStreamer
    build:
      context: .  # Ruta al directorio con el Dockerfile
      dockerfile: Dockerfile_ClientVideo
    container_name: front
    restart: unless-stopped
  #  ports:
      #- 10000:10000
      #- 10001:10001
      #- 10002:10002
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=192.168.1.74:0.0
>>>>>>> 03022cd939abe2f3f7bc1d77299404bf0b988796
    network_mode: "host"
 
  front_web:
      build:
        context: .
        dockerfile: ./Dockerfile_ClienteWeb
      container_name: front_web
      depends_on:
        - db
      ports:
        - 8000:8000
        - 5000:5000
        - 9000:9000
        - 8001:8001
        - 5005:5005
      volumes:
        - ./front_web:/front_web

      environment:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_USER_ADMIN: ${DB_USER_ADMIN}

        DB_HOST: ${DB_HOST}
        DEBUG: ${DEBUG}
        SECRET_KEY: ${SECRET_KEY}

  db:
    image: mariadb
    container_name: ${DB_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 127.0.0.1:3310:3306

volumes:
  db:
