FROM debian:bookworm-slim

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    apache2 \
    python3 \
    python3-pip \
    python3-dev \
    build-essential pkg-config \
    libcairo2-dev \
    python3-venv \
    libmariadb-dev \
    libapache2-mod-wsgi-py3 \
    pkg-config \
    python3-gi libgirepository1.0-dev \
    gir1.2-gstreamer-1.0 python3-gst-1.0 \
    gstreamer1.0-tools gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly gstreamer1.0-libav \
    gcc 

# Configure timezone
ENV TZ=America/Mexico_City
RUN ln -snf  /etc/l/usr/share/zoneinfo/$TZocaltime && echo $TZ > /etc/timezone

WORKDIR /front_web

RUN python3 -m venv /env
#RUN . /env/bin/activate

ENV PATH="/env/bin:$PATH"

#RUN mkdir /app/media && chown :www-data /app/media -R && chmod 775 /app/media -R
RUN /env/bin/pip install --upgrade pip
RUN /env/bin/pip install --no-cache-dir Django==5.1
RUN /env/bin/pip install --no-cache-dir mysqlclient==2.2.4
RUN /env/bin/pip install --no-cache-dir channels
RUN /env/bin/pip install --no-cache-dir channels_redis
RUN /env/bin/pip install --no-cache-dir daphne
RUN /env/bin/pip install --no-cache-dir whitenoise
RUN /env/bin/pip install --no-cache-dir PyGObject==3.50
RUN /env/bin/pip install --no-cache-dir flake8
RUN /env/bin/pip install --no-cache-dir coverage

CMD [ "apachectl", "-D", "FOREGROUND" ]

