# Imagen base oficial de Ubuntu
FROM ubuntu:20.04

# Evitar preguntas interactivas durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Actualizamos el sistema y instalamos las dependencias necesarias
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    ninja-build \
    meson \
    wget \
    curl \
    libx264-dev \
    libssl-dev \
    pkg-config \
    libglib2.0-dev \
    libgirepository1.0-dev \
    libgtk-3-dev \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libusb-1.0-0-dev \
    libopencv-dev \
    libgstreamer1.0-dev\
    libgstreamer-plugins-base1.0-dev \
    libv4l-dev \
    libudev-dev \
    libjsoncpp-dev \
    libboost-all-dev \
    libsdl2-dev \
    libglew-dev \
    libusb-1.0-0 \
    libjsoncpp-dev \
    libtool \
    autoconf \
    automake \
    && apt-get clean

RUN apt-get update && apt-get install -y gnupg

RUN apt-get install -y software-properties-common

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE \
    || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \ 
    --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE \ 
    && add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u \
    && apt-get install -y librealsense2-utils \
    && apt-get install -y librealsense2-dev \
    && apt-get install -y librealsense2-dkms

RUN apt-get update && apt-get install -y \
gstreamer1.0-plugins-base \
gstreamer1.0-plugins-good \
gstreamer1.0-plugins-bad \
gstreamer1.0-tools \
libgstreamer1.0-dev

# 2. Clonar el repo
WORKDIR /opt
RUN git clone https://github.com/WKDSMRT/realsense-gstreamer.git

# 3. Compilar con meson + ninja
WORKDIR /opt/realsense-gstreamer
RUN meson setup builddir --prefix=/usr && \
    ninja -C builddir && \
    ninja -C builddir install

WORKDIR /gstreamer

# Copiar scripts o archivos de configuración (si se necesitan)
COPY ./gstreamer/start_gstreamer.sh /gstreamer/start_gstreamer.sh
RUN chmod +x /gstreamer/start_gstreamer.sh

ENTRYPOINT ["/gstreamer/start_gstreamer.sh"]
