# Generated by Django 5.1 on 2025-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(max_length=50)),
                ('nombreArchivo', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=255)),
                ('fechaGrabacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
